### ISSUE TITLE
Alert rather than notification

### ISSUE THREAD

**Issue by proffapt** [proffapt/pomodoro-cli#2]
This is needed to get the focus of user to the timer notification at any cost.
The alert should have a custom warning logo / icon with a button to accept the timer.

**Comment by CS50X-RGB** [comment]
Can i get this issue??

**Comment by proffapt** [comment]
> Can i get this issue??

Best of luck!!

**Comment by CS50X-RGB** [comment]
I am able to add icon to the notification but cant add the any button because it needs gksudo which is not available for ubantu  right now and moreover i am editing the code but now changes are performed during execution of code plz help

**Comment by proffapt** [comment]
> I am able to add icon to the notification but cant add the any button because it needs gksudo which is not available for ubantu right now

This has been replied in slack.

> i am editing the code but now changes are performed during execution of code plz help

Didn't get you..
