### ISSUE TITLE
[HomeBrew]: Configure installation via homebrew

### ISSUE THREAD

**Issue by proffapt** [proffapt/pomodoro-cli#6]
Tap Repository: https://github.com/proffapt/homebrew-brewtap

**Comment by chandakanup** [comment]
I want to work on this project. Will you pls assign this task to me

**Comment by proffapt** [comment]
Ok, have joined for kwoc and the slack channel?

**Comment by proffapt** [comment]
> I want to work on this project. Will you pls assign this task to me

Ok, have joined for kwoc and the slack channel?

**Comment by proffapt** [comment]
@chandakanup any updates?

**Comment by proffapt** [comment]
> I searched on many websites and videos but I am not sure how to proceed.

You still haven't achieved the endurance to read documentation.. brew.sh has the docs to create formulas

**Comment by proffapt** [comment]
https://docs.brew.sh/Formula-Cookbook

**Comment by proffapt** [comment]
Not Interested in this project anymore.
